import { ThemeProvider } from "@/components/ThemeProvider";
import "../globals.css";
import { Metadata } from "next";
import TheFooter from "@/components/TheFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body cz-shortcut-listen="true">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>{children}</main>
          <TheFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
